name: Python Lint

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Node.js (for pyright)
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install pyright
        run: npm install -g pyright

      - name: Run pyright
        run: pyright
