name: Python Lint

on:
  push:
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js (for pyright)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pyright
        run: npm install -g pyright

      - name: Run pyright
        run: pyright
