name: Create Release Assets

on:
  push:
    tags:
      - '*'  # Trigger on any tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run packaging script
        run: bash ./package.sh

      - name: Upload release assets & generate notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/Unlocker-Windows-*.zip
            release/Unlocker-Linux-*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
