name: Windows Build & Pyright Check

on:
  pull_request:
      branches:
        - main
      paths:
        - '**/*.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js (for pyright)
        uses: actions/setup-node@v5
        with:
            # use the latest Node.js available on the runner/tool-cache
            node-version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pyright
        run: npm install -g pyright

      - name: Run Pyright type check
        run: pyright **/*.py

      - name: Install PyInstaller (latest)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows executables
        run: ./win-build.cmd

      - name: Upload build artifacts for debugging
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: |
            *.exe
